# Use an official Python 3 image as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Specify the command to run when the container starts
CMD ["python", "./server.py"]
